---
kind: pipeline
name: default

clone:
  depth: 50

steps:
- name: install
  image: node:14-alpine
  commands: ["npm ci"]

- name: test
  image: node:14-alpine
  commands: ["npm run test -s"]

- name: release
  image: livingdocs/semantic-release:v1.0.0
  environment:
    GH_TOKEN:
      from_secret: gh_token
    NPM_TOKEN:
      from_secret: npm_token

trigger:
  event: [push]
---
kind: signature
hmac: df53999b1e03687c1cb844cded538caa1d59b1485ca547a5f1c965293eb9eb1c

...
